version: 0.2

#env:
#  parameter-store:
#    CLIENTID: "/iam/auth0-deploy/$ENV/AUTH0_RULE_DEPLOY_CLIENTID"
#    CLIENTSECRET: "/iam/auth0-deploy/$ENV/AUTH0_RULE_DEPLOY_CLIENTSECRET"
#    URI: "/iam/auth0-deploy/$ENV/AUTH0_URI"
phases:
  build:
    commands:
      - apt-get update && apt-get install jq
      # We can't use env: parameter-store for getting these values because it doesn't support variable substitution
      - CLIENTID=$(aws ssm get-parameter --name "/iam/auth0-deploy/$ENV/AUTH0_RULE_DEPLOY_CLIENTID" --with-decryption | jq ".Parameter.Value")
      - CLIENTSECRET=$(aws ssm get-parameter --name "/iam/auth0-deploy/$ENV/AUTH0_RULE_DEPLOY_CLIENTSECRET" --with-decryption | jq ".Parameter.Value")
      - make install
  post_build:
    commands:
      - make CLIENTID=${CLIENTID} CLIENTSECRET=${CLIENTSECRET} URI=${URI} "deploy-$ENV"
